name: "Lint"
on: [push]
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout repository"
        uses: actions/checkout@v3
      - name: "Setup Python"
        uses: actions/setup-python@v3
        with:
          python-version: "3.9"
      - name: "Install poetry"
        uses: snok/install-poetry@v1
        with:
          virtualenvs-create: true
          virtualenvs-in-project: true
      - name: "Load cached venv"
        id: load-cached-venv
        uses: actions/cache@v3
        with:
          path: .venv
          key: venv-${{ runner.os }}-${{ hashFiles('**/poetry.lock') }}
      - name: Install dependencies
        run: poetry install
        if: steps.load-cached-venv.outputs.cache-hit != 'true'
      - name: "Lint"
        run: poetry run poe lint
